cc_binary(
  name="proto_flatten",
  srcs=[
    "proto_flatten.cpp",
    "proto_utils_comm.h",
  ],
  deps=[
    "@com_google_protobuf//:protobuf",
    "@boost//:algorithm",
    "@boost//:filesystem",
    "@boost//:program_options",
  ],
  copts=[
    "-std=c++11",
  ],
  linkopts=[],
)
